version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: aposentprev
    ports:
      - "82:3306"
  app:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
  web:
    build: ./php/
    #image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ../:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true
